### PR TITLE
make the color of speed to white in ex

### PR DESCRIPTION
**Pull request by simon300000**
Before:

After:

### CODE REVIEW

**Comment by ccloli** [comment]
Looks like it's just happen in Safari, only Safari (or on macOS) has this UI. Firefox uses the system UI which on Windows its background is white. And Chrome uses its own UI and its background is also white.
Chrome: 
image
Firefox (I changed Windows theme, so its foreground should be green in original system): 
image

**Comment by ccloli** [comment]
Maybe use a custom `<progress>` UI is better to fix the differences in different browser/system, not to changed the color of text. I'll try it later this day, anyway thanks for your contribution. :-)

**Comment by simon300000** [comment]
Oh I don't know this is different between browsers, sorry for that

**Comment by ccloli** [comment]
Added a custom UI of `progress` (not build, run `build.sh` to get user.js), have a try and check if it works :-)

**Pull request closed without merging**
